export interface profile {
    billingCategory : string,
    dateOfBirth : string,
    dateOfJoining : string,
    designation : string,
    employeeId : string,
    employmentType : string,
    firstName : string,
    fullName : string,
    gender : string,
    hrbpName : string,
    lastName : string,
    middleName : string,
    mustChangePassword : boolean,
    officialEmailId : string,
    contactNumber : string,
    practice : string,
    practiceLeaderName : string,
    projectManagerName : string,
    region : string,
    reportingManager : string,
    role : string,
    status : string,
    subPractice : string,
}
